language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install --upgrade setuptools
  - pip install coveralls
  - pip install -e .
  - pip list

script:
  - ls
  - python setup.py test
  - coverage run --source="sirtalkalot.bots,sirtalkalot.services,sirtalkalot.websocket" setup.py test
  - ls -all
  - cat .coverage

after_success: coveralls

deploy:
  provider: pypi
  user: nicoretti
  password:
    secure: "ZcO/pcRI4d60cLOUPSJHPpv+lF+GBRYixDbR/W7hjeUbu5zknEYTb26nydLRXdbtOEgkQjLO0Jl5s/krUKygqdguU9svYSprqdAz81UsxAkN+OemAEvT7xon3dI9RPv1VIRNEVBRc3KV0T529bAw2Tl3ftR5iKrKBejXdGNXErM="
  on:
    tags: true

